// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {firewall} from '../models';
import {ports} from '../models';

export function AddRule(arg1:firewall.FirewallRule):Promise<void>;

export function AllowApp(arg1:string):Promise<void>;

export function BlockApp(arg1:string):Promise<void>;

export function ChangeServicePort(arg1:string,arg2:number):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function GetFirewallStatus():Promise<boolean>;

export function GetRules(arg1:string,arg2:number):Promise<Array<firewall.FirewallRule>>;

export function GetServicePorts():Promise<Array<ports.ServicePort>>;

export function IsAdmin():Promise<boolean>;

export function OpenExplorer(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function ResetFirewall():Promise<void>;

export function SetFirewallEnabled(arg1:boolean):Promise<void>;

export function ToggleRule(arg1:string,arg2:boolean):Promise<void>;
