// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1) {
  return window['go']['main']['App']['AddRule'](arg1);
}

export function AllowApp(arg1) {
  return window['go']['main']['App']['AllowApp'](arg1);
}

export function BlockApp(arg1) {
  return window['go']['main']['App']['BlockApp'](arg1);
}

export function ChangeServicePort(arg1, arg2) {
  return window['go']['main']['App']['ChangeServicePort'](arg1, arg2);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function GetFirewallStatus() {
  return window['go']['main']['App']['GetFirewallStatus']();
}

export function GetRules(arg1, arg2) {
  return window['go']['main']['App']['GetRules'](arg1, arg2);
}

export function GetServicePorts() {
  return window['go']['main']['App']['GetServicePorts']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function OpenExplorer(arg1) {
  return window['go']['main']['App']['OpenExplorer'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ResetFirewall() {
  return window['go']['main']['App']['ResetFirewall']();
}

export function SetFirewallEnabled(arg1) {
  return window['go']['main']['App']['SetFirewallEnabled'](arg1);
}

export function ToggleRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleRule'](arg1, arg2);
}
