// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {firewall} from '../models';

export function AddRule(arg1:firewall.FirewallRule):Promise<void>;

export function AllowApp(arg1:string):Promise<void>;

export function BlockApp(arg1:string):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function GetRules(arg1:string,arg2:number):Promise<Array<firewall.FirewallRule>>;

export function IsAdmin():Promise<boolean>;

export function ToggleRule(arg1:string,arg2:boolean):Promise<void>;
